baseurl = "/"
languageCode= "fr"
title = "Hugo web Site"
theme = "mediumish-gohugo-theme"

[params]
  intro = true
    headline = "Hugo + Cockpit"
    description = "Un editeur web pour Hugo"
    # description = "Slimy things oozing my brain"
    github = "https://github.com/soph25"


