baseurl = "/"
languageCode= "fr"
title = "My New Hugo Site"
theme = "mediumish-gohugo-theme"

[params]
  logo = "/images/icon.png"
  description ="the clean blog!"
  mailchimp = "you can provide a mailchimp-link here, see below"
  mailprotect = "you can provide a protector-name here, see below"

[params.index]
  picture = "/images/author.png"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading'''
  alertbar = true
